backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "static/img" # Media files will be stored in the repo under images/uploads

collections:
  - name: "pages"
    label: "Page"
    folder: "pages"
    create: false # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "hidden" }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "hidden" }
          - { label: "Order", name: "order", widget: "hidden", default: 0 }
      - label: "Links" 
        name: "links"
        widget: "object"
        fields:
        - { label: "Link Label", name: "linkLabel", widget: "string" }
        - { label: "Link URL", name: "linkUrl", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
